// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ye-36BHrlum6ildTDN5LPI_XW2gJY08',
    appId: '1:816494282133:web:0636332a26b3883a52229c',
    messagingSenderId: '816494282133',
    projectId: 'hostel-finder-171db',
    authDomain: 'hostel-finder-171db.firebaseapp.com',
    storageBucket: 'hostel-finder-171db.appspot.com',
    measurementId: 'G-W3FCCQZRDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb1JxWVqRHOIqIyxIng5M09h9uhk5EAL8',
    appId: '1:816494282133:android:566dc79fae2e333252229c',
    messagingSenderId: '816494282133',
    projectId: 'hostel-finder-171db',
    storageBucket: 'hostel-finder-171db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH3c7kfddQwmLzc8YeMVwl8WkLtT25HfI',
    appId: '1:816494282133:ios:b13d52584b7bf7f752229c',
    messagingSenderId: '816494282133',
    projectId: 'hostel-finder-171db',
    storageBucket: 'hostel-finder-171db.appspot.com',
    iosClientId: '816494282133-uipk4e5d8bvj6tuju6vl1t1nfdlp8u5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelFinderAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH3c7kfddQwmLzc8YeMVwl8WkLtT25HfI',
    appId: '1:816494282133:ios:ac7b338dd3c9888c52229c',
    messagingSenderId: '816494282133',
    projectId: 'hostel-finder-171db',
    storageBucket: 'hostel-finder-171db.appspot.com',
    iosClientId: '816494282133-roq0ssau71cod47uvuqp3nbbl1qgj7eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostelFinderAdmin.RunnerTests',
  );
}
